DapperCoreMVC/Models/ErrorViewModel.cs
using System;

namespace DapperCoreMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DapperCoreMVC/Models/Herbs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DapperCoreMVC.Models
{
    public class Herbs
    {
        [Key]
        public int HerbId { get; set; }
        [Required]
        [Display(Name="Název")]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Popis")]
        public string Info { get; set; }
        [Required]
        [Display(Name = "Léčivé účinky")]
        public string Healing { get; set; }
    }
}

DapperCoreMVC/Controllers/HerbsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DapperCoreMVC.Data;
using DapperCoreMVC.Models;
using DapperCoreMVC.Repository;

namespace DapperCoreMVC.Controllers
{
    public class HerbsController : Controller
    {
        private readonly IHerbRepository _herbRepo;

        public HerbsController(IHerbRepository herbRepo)
        {
            _herbRepo = herbRepo;
        }

        // GET: Herbs
        public async Task<IActionResult> Index()
        {
            return View(_herbRepo.GetAll());
        }

        // GET: Herbs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var herbs = _herbRepo.Find(id.GetValueOrDefault());
               
            if (herbs == null)
            {
                return NotFound();
            }

            return View(herbs);
        }

        // GET: Herbs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Herbs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HerbId,Name,Info,Healing")] Herbs herbs)
        {
            if (ModelState.IsValid)
            {
                _herbRepo.Add(herbs);
                return RedirectToAction(nameof(Index));
            }
            return View(herbs);
        }

        // GET: Herbs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var herbs = _herbRepo.Find(id.GetValueOrDefault());
            if (herbs == null)
            {
                return NotFound();
            }
            return View(herbs);
        }

        // POST: Herbs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HerbId,Name,Info,Healing")] Herbs herbs)
        {
            if (id != herbs.HerbId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _herbRepo.Update(herbs);
                return RedirectToAction(nameof(Index));
            }
            return View(herbs);
        }

        // GET: Herbs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _herbRepo.Remove(id.GetValueOrDefault());
            return RedirectToAction(nameof(Index));
        }       
    }
}

DapperCoreMVC/Controllers/HomeController.cs
using DapperCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DapperCoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DapperCoreMVC/Views/Herbs/Create.cshtml
@model DapperCoreMVC.Models.Herbs

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Herbs</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" />
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Healing" class="control-label"></label>
                <input asp-for="Healing" class="form-control" />
                <span asp-validation-for="Healing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DapperCoreMVC/Views/Herbs/Delete.cshtml
@model DapperCoreMVC.Models.Herbs

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Herbs</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Info)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Healing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Healing)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="HerbId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DapperCoreMVC/Views/Herbs/Details.cshtml
@model DapperCoreMVC.Models.Herbs

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Herbs</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Info)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Healing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Healing)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.HerbId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DapperCoreMVC/Views/Herbs/Edit.cshtml
@model DapperCoreMVC.Models.Herbs

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Herbs</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HerbId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" />
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Healing" class="control-label"></label>
                <input asp-for="Healing" class="form-control" />
                <span asp-validation-for="Healing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DapperCoreMVC/Views/Herbs/Index.cshtml
@model IEnumerable<DapperCoreMVC.Models.Herbs>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Info)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Healing)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Info)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Healing)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.HerbId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.HerbId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.HerbId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DapperCoreMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Herbář</h1>
    <p>Nácvik .NET Core MVC aplikace za použití: <strong>DAPPER</strong></p>
    <p>zdroj: <a href="https://www.youtube.com/watch?v=IVsN0WlufWc&ab_channel=BhrugenPatel" target="_blank">Bhrugen Patel</a></p>
</div>

DapperCoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DapperCoreMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DapperCoreMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Herbs" asp-action="Index">Byliny</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DapperCoreMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>